### ISSUE TITLE
In test environment, logger shouldn't be used

### ISSUE THREAD

**Issue by markelog** [markelog/example#2]
Should check environment variable and not initialise logger middleware

**Comment by viestat** [comment]
Do something!
![](https://camo.githubusercontent.com/4e07a7d190ed9d3a622bbf33f2c80f1a31f7d7fb/68747470733a2f2f33382e6d656469612e74756d626c722e636f6d2f74756d626c725f6d32776b70383937725931727072786b726f315f3530302e676966)
